name: Bump and build

on:
  push:
    branches:
      - main
      - develop
      - release

env:
  FINDOX_APP_NAME: "api"
  FINDOX_APP_PACKAGE_PATH: "/app/api"
  BUILD_CMD: "FinDox.Server"
  BUILD_OUTPUT_DIR: "./api"
  BUILD_RELEASE_DIR: "./release/api"
  NETCORE_VERSION: "6.0.x"

jobs:

  env_check:
    runs-on: ubuntu-latest
    steps:
      - name: Environment check on branch
        id: branch_check
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "env_name=prod" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" = "refs/heads/release" ]; then
            echo "env_name=stg" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            echo "env_name=qa" >> $GITHUB_OUTPUT
          else
            echo "env_name=undefined" >> $GITHUB_OUTPUT
          fi    
              
      - name: Use environment setup in previous step
        run: echo "Setting up environment ${{ steps.branch_check.outputs.env_name }}"

    outputs:
      env_name: ${{ steps.branch_check.outputs.env_name }}
 
  create_tag:
    runs-on: ubuntu-latest
    needs: env_check
    permissions:
      contents: write
    steps:

      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main, master
          pre_release_branches: develop
          default_bump: minor
          
      - name: Create a GitHub release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.env_check.outputs.env_name }}-${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ needs.env_check.outputs.env_name }}-${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: image_tag
        id: image_tag
        shell: bash
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ github.ref }}" = "refs/heads/master" ] || [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "image_tag=release-${{ steps.tag_version.outputs.new_tag }}" >> $GITHUB_OUTPUT
          else
            echo "image_tag=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

  get_last_tag:
    name: Get last tag
    runs-on: ubuntu-latest
    needs: env_check
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Get latest staging tag
        uses: rmeneely/git-last-tag@v1
        with:
          tag_pattern: '${{ needs.env_check.outputs.env_name }}-v[0-9]*.[0-9]*.[0-9]*'
                
      - name: Print latest tag
        run: |
          echo ${{ env.LAST_TAG }}
    
  build:
    runs-on: ubuntu-latest
    needs: get_last_tag
    permissions:
      contents: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.LAST_TAG }}
          
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"
                  
      - name: Show dotnet version
        run: dotnet --version
