name: Bump version

on:
  push:
    branches:
      - main
      - develop
      - release

jobs:

  env_check:
    runs-on: ubuntu-latest
    steps:
      - name: Environment check on branch
        id: branch_check
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "env_name=prod" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" = "refs/heads/release" ]; then
            echo "env_name=stg" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            echo "env_name=qa" >> $GITHUB_OUTPUT
          else
            echo "env_name=undefined" >> $GITHUB_OUTPUT
          fi    
              
      - name: Use environment setup in previous step
        run: echo "Setting up environment ${{ steps.branch_check.outputs.env_name }}"

    outputs:
      env_name: ${{ steps.branch_check.outputs.env_name }}
 
  build:
    runs-on: ubuntu-latest
    needs: env_check
    permissions:
      contents: write
    steps:

      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main, master
          pre_release_branches: develop
          default_bump: minor
          
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.env_check.outputs.env_name }}-${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ needs.env_check.outputs.env_name }}-${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: image_tag
        id: image_tag
        shell: bash
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ github.ref }}" = "refs/heads/master" ] || [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "image_tag=prod-${{ steps.tag_version.outputs.new_tag }}" >> $GITHUB_OUTPUT
          else
            echo "image_tag=${{ needs.env_check.outputs.env_name }}-${{ steps.tag_version.outputs.new_tag }}" >> $GITHUB_OUTPUT
          fi

      - name: Print tag
        id: print_tag
        shell: bash
        run: |
          echo ${{ env.image_tag }}