name: Get file hash

on:
  workflow_dispatch:

jobs:
    get_hash:
        runs-on: ubuntu-latest
        steps:
            - name: Get file hash
              run: |
                wget https://raw.githubusercontent.com/mmestrovic/ghtags/main/README.md
                sha256sum README.md
