name: Test new rules

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Select an environment
        type: choice
        required: true
        default: ""
        options:
          - qa
          - staging

  workflow_call:

jobs:

  env_check:
    name: Environment check
    runs-on: ubuntu-latest
    steps:
      - name: Set deployment parameters (env_name and deploy_branch)
        id: env_setup
        run: |
          echo "Running on branch ${{ github.ref }}"

          if [ "${{ inputs.environment }}" = "staging" ]; then
            echo "env_name=staging" >> $GITHUB_OUTPUT
          elif [ "${{ inputs.environment }}" = "qa" ]; then
            echo "env_name=qa" >> $GITHUB_OUTPUT
          else
            echo "You need to select environment"
            exit 1
          fi

      - name: Use environment setup in previous step
        run: echo "Setting up environment ${{ steps.env_setup.outputs.env_name }}"

    outputs:
      env_name: ${{ steps.env_setup.outputs.env_name }}

  deployment_check:
    name: Deployment check
    runs-on: ubuntu-latest
    needs: env_check
    permissions:
      contents: write
    steps:

      - name: Deployment from Staging or QA
        if: ${{ startsWith(github.ref, 'refs/tags/staging') || startsWith(github.ref,'refs/tags/qa') }}
        shell: bash
        run: |
          set -e
          echo "OK: Deployment from Staging or QA."
          exit 0

      - name: Deployment not from Staging or QA
        if: ${{ ! startsWith(github.ref, 'refs/tags/staging') && ! startsWith(github.ref,'refs/tags/qa') }}
        shell: bash
        run: |
          set -e
          echo "Error: Deployment not from Staging or QA."
          exit 1


