name: Set env
on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Branch check
      id: branch_check
      run: |
        echo "Running on branch ${{ github.ref }}"

    - uses: actions/checkout@v2
    - name: Set GITHUB_SHA_SHORT
      run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
    
    - name: Set myValue
      run: echo "myValue=${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Set isTag
      id: set_istag 
      run: echo "isTag=${{ startsWith(github.ref, 'refs/tags/') }}" >> $GITHUB_ENV 
    
    - name: Set isBranch
      id: set_isbranch 
      run: echo "isBranch=${{ startsWith(github.ref, 'refs/heads/') }}" >> $GITHUB_ENV 
    
    - name: Test
      run: |
        echo $GITHUB_SHA_SHORT
        echo $myValue
        echo $isTag
        echo $isBranch


    